# Development-specific configuration
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=false
spring.devtools.restart.poll-interval=1s
spring.devtools.restart.quiet-period=400ms

# Enable debugging
logging.level.com.team44.isa_youtubeich=DEBUG
logging.level.org.springframework.cache=TRACE
spring.jpa.show-sql=true

spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true