# Usage: SPRING_PROFILES_ACTIVE=dev,dev-reset (or -Dspring-boot.run.profiles=dev,dev-reset)

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
